# Generated by Django 4.2.11 on 2025-06-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_seller_user_userstory_sellitem_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='assets/games/images/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='assets/games/videos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/users/images/'),
        ),
    ]
