# Generated by Django 5.2.1 on 2025-07-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_game_image_alter_game_video_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='static/images/games/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/videos/games/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/users/'),
        ),
    ]
