# Generated by Django 5.2.1 on 2025-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_game_image_alter_game_video_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='game',
            name='sell_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
