# Generated by Django 5.2.1 on 2025-07-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_game_avg_rating_game_sell_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='game',
            name='middle_price',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='game',
            name='min_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
